name: Semantic release

on:
  workflow_dispatch:


permissions:
  contents: write
  id-token: write # Required for OIDC and trusted publishing

jobs:
  release:
    name: Semantic release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Node.js per package.json
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Update npm # To ensure npm 11.5.1 or later is installed for Trusted publishing
        shell: bash
        run: npm install -g npm@latest

      - name: Install dependencies
        shell: bash
        run: npm i

      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: npx semantic-release
  test-get-version:
    needs: ['release']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Pull latest commits
        run: git pull origin main
      - name: Print latest commit
        run: |
          echo "Latest commit:"
          git log -1 --pretty=format:"%H%nAuthor: %an%nDate: %ad%nMessage: %s"
